name: Prod-FR Workflow

on:
  repository_dispatch:
    types:
      - trigger-prod-FR

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Echo Payload Commit Message from Main
        run: |
          echo "Payload commit message from main: ${{ github.event.client_payload.commit_message }}"

      # Checkout and process Prod-FR branch
      - name: Checkout code to Prod-FR
        uses: actions/checkout@v3
        with:
          ref: Prod-FR  # Checkout to the Prod-FR branch

      - name: Print actual commit message and hash for Prod-FR
        run: |
          echo "Actual commit message for Prod-FR: $(git log -1 --format=%s)"
          echo "Current HEAD commit hash for Prod-FR: $(git rev-parse HEAD)"
          
      - name: Print payload commit message for Prod-FR
        run: |
          echo "Payload commit message for Prod-FR: ${{ github.event.client_payload.sc_ui_dispatch_commits['Prod-FR'] }}"

      - name: Install npm dependencies
        run: |
          npm install
          
      - name: Start the application
        run: |
          npm start
          
      - name: List all files in Prod-FR directory
        run: |
          echo "Files in Prod-FR:"
          ls -ltr
