name: Prod-EN Workflow

on:
  repository_dispatch:
    types:
      - trigger-prod-EN

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Echo Payload Commit Message from Main
        run: |
          echo "Payload commit message from main: ${{ github.event.client_payload.data[0].commit_message }}"

      - name: Checkout code to Prod-EN
        if: ${{ github.event.client_payload.data[0].trigger-branch == 'Prod-EN' }}
        uses: actions/checkout@v3
        with:
          ref: Prod-EN

      - name: Print actual commit message and hash for Prod-EN
        if: ${{ github.event.client_payload.data[0].trigger-branch == 'Prod-EN' }}
        run: |
          echo "Actual commit message for Prod-EN: $(git log -1 --format=%s)"
          echo "Current HEAD commit hash for Prod-EN: $(git rev-parse HEAD)"
        
      - name: Print payload commit message for Prod-EN
        if: ${{ github.event.client_payload.data[0].trigger-branch == 'Prod-EN' }}
        run: |
          echo "Payload commit message for Prod-EN: ${{ github.event.client_payload.data[0].sc_ui_dispatch_commits['Prod-EN'] }}"
        shell: bash

      - name: Navigate to Node Project Directory
        if: ${{ github.event.client_payload.data[0].trigger-branch == 'Prod-EN' }}
        run: |
          cd my-node-project &&
             npm install &&
             npm start

      - name: List all files in Prod-EN directory
        if: ${{ github.event.client_payload.data[0].trigger-branch == 'Prod-EN' }}
        run: |
          echo "Files in Prod-EN:"
          ls -ltr
