name: Prod-FR Workflow

on:
  repository_dispatch:
    types:
      - trigger-prod-FR

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Echo Payload Commit Message from Main
        run: |
          echo "Payload commit message from main: ${{ github.event.client_payload.data[0].commit_message }}"

      - name: Checkout code to Prod-FR
        if: ${{ github.event.client_payload.data[0].trigger-branch == 'Prod-FR' }}
        uses: actions/checkout@v3
        with:
          ref: Prod-FR

      - name: Print actual commit message and hash for Prod-FR
        if: ${{ github.event.client_payload.data[0].trigger-branch == 'Prod-FR' }}
        run: |
          echo "Actual commit message for Prod-FR: $(git log -1 --format=%s)"
          echo "Current HEAD commit hash for Prod-FR: $(git rev-parse HEAD)"
          
      - name: Print payload commit message for Prod-FR
        if: ${{ github.event.client_payload.data[0].trigger-branch == 'Prod-FR' }}
        run: |
          echo "Payload commit message for Prod-FR: ${{ github.event.client_payload.data[0].sc_ui_dispatch_commits['Prod-FR'] }}"

      - name: Navigate to Node Project Directory
        if: ${{ github.event.client_payload.data[0].trigger-branch == 'Prod-FR' }}
        run: |
          cd my-node-project &&
          npm install &&
          npm start

      - name: List all files in Prod-FR directory
        if: ${{ github.event.client_payload.data[0].trigger-branch == 'Prod-FR' }}
        run: |
          echo "Files in Prod-FR:"
          ls -ltr
