name: Prod-EN Workflow

on:
  repository_dispatch:
    types:
      - trigger-prod-EN

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Echo Payload Commit Message from Main
        run: |
          echo "Payload commit message from main: ${{ github.event.client_payload.commit_message }}"

      # Checkout and process Prod-EN branch
      - name: Checkout code to Prod-EN
        uses: actions/checkout@v3
        with:
          ref: Prod-EN  # Checkout to the Prod-EN branch

      - name: Print actual commit message and hash for Prod-EN
        run: |
          echo "Actual commit message for Prod-EN: $(git log -1 --format=%s)"
          echo "Current HEAD commit hash for Prod-EN: $(git rev-parse HEAD)"
          
      - name: Print payload commit message for Prod-EN
        run: |
          echo "Payload commit message for Prod-EN: ${{ github.event.client_payload.sc_ui_dispatch_commits['Prod-EN'] }}"

      - name: Install npm dependencies
        run: |
          npm install
          
      - name: Start the application
        run: |
          npm start
          
      - name: List all files in Prod-EN directory
        run: |
          echo "Files in Prod-EN:"
          ls -ltr
