name: Prod-EN Workflow

on:
  repository_dispatch:
    types:
      - trigger-prod-EN

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Echo Payload Commit Message from Main
        run: |
          echo "Payload commit message from main: ${{ github.event.client_payload.commit_message }}"
          echo "Prod-EN commit message from payload: ${{ github.event.client_payload.sc_ui_dispatch_commits['Prod-EN'] }}"

      - name: Checkout code to Prod-EN
        uses: actions/checkout@v3
        with:
          ref: Prod-EN  # Ensure the branch exists and is correctly named

      - name: Print Payload and Repository Commit Messages
        run: |
          # Print Payload Commit Messages
          echo "Payload commit message from payload: ${{ github.event.client_payload.commit_message }}"
          echo "Prod-EN commit message from payload: ${{ github.event.client_payload.sc_ui_dispatch_commits['Prod-EN'] }}"
          
          # Print Repository Commit Messages
          echo "Actual commit message for Prod-EN: $(git log -1 --format=%s)"
          echo "Current HEAD commit hash for Prod-EN: $(git rev-parse HEAD)"

      - name: Install npm dependencies
        run: |
          npm install
          
      - name: Start the application
        run: |
          npm start
          
      - name: List all files in Prod-EN directory
        run: |
          echo "Files in Prod-EN:"
          ls -ltr
